#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhucShoes.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_BanGiay")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGiay(Giay instance);
    partial void UpdateGiay(Giay instance);
    partial void DeleteGiay(Giay instance);
    partial void InsertHangGiay(HangGiay instance);
    partial void UpdateHangGiay(HangGiay instance);
    partial void DeleteHangGiay(HangGiay instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_BanGiayConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Giay> Giays
		{
			get
			{
				return this.GetTable<Giay>();
			}
		}
		
		public System.Data.Linq.Table<HangGiay> HangGiays
		{
			get
			{
				return this.GetTable<HangGiay>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Giay")]
	public partial class Giay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiay;
		
		private string _TenGiay;
		
		private System.Nullable<decimal> _GiaBan;
		
		private string _MaHang;
		
		private string _AnhGiay;
		
		private EntityRef<HangGiay> _HangGiay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiayChanging(string value);
    partial void OnMaGiayChanged();
    partial void OnTenGiayChanging(string value);
    partial void OnTenGiayChanged();
    partial void OnGiaBanChanging(System.Nullable<decimal> value);
    partial void OnGiaBanChanged();
    partial void OnMaHangChanging(string value);
    partial void OnMaHangChanged();
    partial void OnAnhGiayChanging(string value);
    partial void OnAnhGiayChanged();
    #endregion
		
		public Giay()
		{
			this._HangGiay = default(EntityRef<HangGiay>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiay", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiay
		{
			get
			{
				return this._MaGiay;
			}
			set
			{
				if ((this._MaGiay != value))
				{
					this.OnMaGiayChanging(value);
					this.SendPropertyChanging();
					this._MaGiay = value;
					this.SendPropertyChanged("MaGiay");
					this.OnMaGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiay", DbType="VarChar(30)")]
		public string TenGiay
		{
			get
			{
				return this._TenGiay;
			}
			set
			{
				if ((this._TenGiay != value))
				{
					this.OnTenGiayChanging(value);
					this.SendPropertyChanging();
					this._TenGiay = value;
					this.SendPropertyChanged("TenGiay");
					this.OnTenGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Money")]
		public System.Nullable<decimal> GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang", DbType="Char(10)")]
		public string MaHang
		{
			get
			{
				return this._MaHang;
			}
			set
			{
				if ((this._MaHang != value))
				{
					if (this._HangGiay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHangChanging(value);
					this.SendPropertyChanging();
					this._MaHang = value;
					this.SendPropertyChanged("MaHang");
					this.OnMaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhGiay", DbType="VarChar(30)")]
		public string AnhGiay
		{
			get
			{
				return this._AnhGiay;
			}
			set
			{
				if ((this._AnhGiay != value))
				{
					this.OnAnhGiayChanging(value);
					this.SendPropertyChanging();
					this._AnhGiay = value;
					this.SendPropertyChanged("AnhGiay");
					this.OnAnhGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangGiay_Giay", Storage="_HangGiay", ThisKey="MaHang", OtherKey="MaHang", IsForeignKey=true)]
		public HangGiay HangGiay
		{
			get
			{
				return this._HangGiay.Entity;
			}
			set
			{
				HangGiay previousValue = this._HangGiay.Entity;
				if (((previousValue != value) 
							|| (this._HangGiay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HangGiay.Entity = null;
						previousValue.Giays.Remove(this);
					}
					this._HangGiay.Entity = value;
					if ((value != null))
					{
						value.Giays.Add(this);
						this._MaHang = value.MaHang;
					}
					else
					{
						this._MaHang = default(string);
					}
					this.SendPropertyChanged("HangGiay");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangGiay")]
	public partial class HangGiay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHang;
		
		private string _TenHang;
		
		private string _Logo;
		
		private EntitySet<Giay> _Giays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHangChanging(string value);
    partial void OnMaHangChanged();
    partial void OnTenHangChanging(string value);
    partial void OnTenHangChanged();
    partial void OnLogoChanging(string value);
    partial void OnLogoChanged();
    #endregion
		
		public HangGiay()
		{
			this._Giays = new EntitySet<Giay>(new Action<Giay>(this.attach_Giays), new Action<Giay>(this.detach_Giays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHang
		{
			get
			{
				return this._MaHang;
			}
			set
			{
				if ((this._MaHang != value))
				{
					this.OnMaHangChanging(value);
					this.SendPropertyChanging();
					this._MaHang = value;
					this.SendPropertyChanged("MaHang");
					this.OnMaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHang", DbType="VarChar(30)")]
		public string TenHang
		{
			get
			{
				return this._TenHang;
			}
			set
			{
				if ((this._TenHang != value))
				{
					this.OnTenHangChanging(value);
					this.SendPropertyChanging();
					this._TenHang = value;
					this.SendPropertyChanged("TenHang");
					this.OnTenHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="VarChar(30)")]
		public string Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this.OnLogoChanging(value);
					this.SendPropertyChanging();
					this._Logo = value;
					this.SendPropertyChanged("Logo");
					this.OnLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangGiay_Giay", Storage="_Giays", ThisKey="MaHang", OtherKey="MaHang")]
		public EntitySet<Giay> Giays
		{
			get
			{
				return this._Giays;
			}
			set
			{
				this._Giays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Giays(Giay entity)
		{
			this.SendPropertyChanging();
			entity.HangGiay = this;
		}
		
		private void detach_Giays(Giay entity)
		{
			this.SendPropertyChanging();
			entity.HangGiay = null;
		}
	}
}
#pragma warning restore 1591
